# Generated by Django 4.2.8 on 2023-12-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
                ('descripcion', models.TextField(max_length=100)),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
