# Generated by Django 3.2.4 on 2023-12-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.IntegerField()),
                ('tipo', models.TextField(max_length=100)),
                ('descripcion', models.TextField(max_length=100)),
                ('stock', models.IntegerField()),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
